### PR TITLE
Update metaclass_auth_guard.nl.yml

### PR DESCRIPTION
**Pull request by endroid**
Fixed some minor language errors.

### CODE REVIEW

**Comment by rudott** [comment]
@stof @metaclass-nl is it possible to merge these changes?
Thanks!

**Comment by stof** [comment]
@rudott I'm not a maintainer on this repo at all

**Comment by rudott** [comment]
@stof ok check (sorry ;) ), I saw some commits and noticed that the last commit is aug 2016..

**Comment by stof** [comment]
Yeah, I send 2 small PR a long time ago (fixing a typo in the doc and improving a composer constraint). You contributed more than me in term of modified lines 😄

**Comment by endroid** [comment]
@metaclass-nl Any idea if or when this will be merged. It merely fixes some typos so you should be able to do this blindfolded ;)

**Comment by metaclass-nl** [comment]
Sorry, skipped my attention. Thanks!

**Pull request merged**
